# $Id$
DOC=	design
MASTERDOC=	design.txt

ASCIIDOCFLAGS=	-f design.conf

SRCS= design-docinfo.xml
SRCS+= goals.txt
SRCS+= architecture.txt
SRCS+= data-structures.txt
SRCS+= parsing.txt
SRCS+= coding-style.txt
SRCS+= bibliography.txt
SRCS+= glossary.txt

IMAGES=  architecture/pipeline.pic
IMAGES+= architecture/modular.pic
IMAGES+= architecture/support.pic
IMAGES+= architecture/multi.pic

include ../share/mk/doc.asciidoc.mk
