# $Id$
DOC=	design

MASTERDOC=	book.xml

SRCS=  book.xml
SRCS+= preface.xml
SRCS+= goals/chapter.xml
SRCS+= architecture/chapter.xml
SRCS+= data-structures/chapter.xml
SRCS+= parsing/chapter.xml
SRCS+= coding-style/chapter.xml
SRCS+= bibliography.xml
SRCS+= glossary.xml

IMAGES=  architecture/pipeline.pic
IMAGES+= architecture/modular.pic
IMAGES+= architecture/support.pic
IMAGES+= architecture/multi.pic

include ../share/mk/doc.docbook.mk
