# $Id$
DOC=	manual

MASTERDOC=	book.xml

SRCS=  book.xml
SRCS+= introduction.xml
SRCS+= running/chapter.xml
SRCS+= nasm-language/chapter.xml
SRCS+= nasm-preprocessor/chapter.xml
SRCS+= nasm-directives/chapter.xml
SRCS+= objfmt-bin/chapter.xml
SRCS+= objfmt-coff/chapter.xml
SRCS+= objfmt-elf32/chapter.xml
SRCS+= objfmt-elf64/chapter.xml
SRCS+= objfmt-macho32/chapter.xml
SRCS+= objfmt-macho64/chapter.xml
SRCS+= objfmt-rdf/chapter.xml
SRCS+= objfmt-win32/chapter.xml
SRCS+= objfmt-win64/chapter.xml
SRCS+= objfmt-xdf/chapter.xml
SRCS+= dbgfmt-cv8/chapter.xml
SRCS+= dbgfmt-dwarf2/chapter.xml
SRCS+= dbgfmt-stabs/chapter.xml
SRCS+= arch-x86/chapter.xml

IMAGES=  objfmt-win64/calling-convention.pic
IMAGES+= objfmt-win64/stack-frame-detailed.pic
IMAGES+= arch-x86/x86-registers.pic

include ../share/mk/doc.docbook.mk
